export type article = {
  id: number;
  key: string;
  date: string;
  minutes: number;
  category?: string;
};

export const articles = [
  { id: 1, key: "fleetUtilization", date: "Sep 2026", minutes: 5 },
  { id: 2, key: "fleetEfficiency", date: "Oct 2026", minutes: 6 },
  { id: 3, key: "fleetCosts", date: "Nov 2026", minutes: 7 },
  { id: 4, key: "fleetTechnology", date: "Dec 2026", minutes: 8 },
  { id: 5, key: "fuelCosts", date: "Jan 2027", minutes: 5 },
  { id: 6, key: "fleetManagement", date: "Nov 2026", minutes: 7 },
  { id: 7, key: "fleetAnalytics", date: "Feb 2027", minutes: 6 },
  { id: 8, key: "fleetMaintenance", date: "Mar 2027", minutes: 5 },
  { id: 9, key: "fleetSustainability", date: "Apr 2027", minutes: 7 },
  { id: 10, key: "fleetUtilization", date: "May 2027", minutes: 5 },
  { id: 11, key: "fleetEfficiency", date: "Jun 2027", minutes: 6 },
  { id: 12, key: "fleetCosts", date: "Jul 2027", minutes: 7 },
  { id: 13, key: "fleetTechnology", date: "Aug 2027", minutes: 8 },
  { id: 14, key: "fuelCosts", date: "Sep 2027", minutes: 5 },
  { id: 15, key: "fleetManagement", date: "Oct 2027", minutes: 7 },
  { id: 16, key: "fleetAnalytics", date: "Nov 2027", minutes: 6 },
  { id: 17, key: "fleetMaintenance", date: "Dec 2027", minutes: 5 },
  { id: 18, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 19, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 20, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 21, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 22, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 23, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 24, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 25, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 26, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 27, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 28, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 29, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 39, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 31, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 32, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 33, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 34, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 35, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 36, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 37, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 25, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 26, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 27, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 28, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 29, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 39, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 31, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 32, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 33, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 34, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 35, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 36, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 37, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 25, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 26, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 27, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 28, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 29, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 39, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 31, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 32, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 33, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 34, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 35, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 36, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 37, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 25, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 26, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 27, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 28, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 29, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 39, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 31, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 32, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 33, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 34, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 35, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 36, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 37, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 25, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 26, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 27, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
  { id: 28, key: "fleetSustainability", date: "Jan 2028", minutes: 7 },
  { id: 29, key: "fleetUtilization", date: "Feb 2028", minutes: 5 },
  { id: 39, key: "fleetEfficiency", date: "Mar 2028", minutes: 6 },
  { id: 31, key: "fleetCosts", date: "Apr 2028", minutes: 7 },
  { id: 32, key: "fleetTechnology", date: "May 2028", minutes: 8 },
  { id: 33, key: "fuelCosts", date: "Jun 2028", minutes: 5 },
  { id: 34, key: "fleetManagement", date: "Jul 2028", minutes: 7 },
  { id: 35, key: "fleetAnalytics", date: "Aug 2028", minutes: 6 },
  { id: 36, key: "fleetMaintenance", date: "Sep 2028", minutes: 5 },
  { id: 37, key: "fleetSustainability", date: "Oct 2028", minutes: 7 },
] as article[];
